[package]
name = "cbserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbprotolib = { path = "../cbprotolib" }
mysql = "*"
tokio = { version = "1", features = ["full"] }
tonic = "*"
uuid = "*"
